#!/bin/sh

#set -e
#set -x 

#confdir="/etc/pf/"
confdir="."
#rulesdir="/etc/pf/"
rulesdir="."
#rulesdir="/etc/pf/lib"
libdir="./lib"

#tables="filter nat mangle"
tables="filter"

conffile="${confdir}/pf.conf"

. "${confdir}/${conffile}" 
. "${libdir}/functions.sh"

rulesfile="${cachedir}/pf.rules"
mkdir -p "${cachedir}"

[ -x "${libdir}/$(basename "${1}")" ] || {
	echo "$0: function does not exist."
	exit 1
} >&2 && {
	. "${libdir}/$(basename "${1}")"
}


