#!/bin/sh

basename="${0##*/}"
target_mode="${basename##*-}"

rootdev="$(awk -F '[ ,]' '/^\/dev\/[0-9a-z]+ \/ [0-9a-z]+/ {print $1}' /proc/mounts)"
mode="$(awk -F '[ ,]' '/^\/dev\/[0-9a-z]+ \/ [0-9a-z]+/ {print $4}' /proc/mounts)"

echo "$basename: $rootdev $mode"

mount -o remount,$target_mode /
#mount -o remount,$target_mode $rootdev

mode="$(awk -F '[ ,]' '/^\/dev\/[0-9a-z]+ \/ [0-9a-z]+/ {print $4}' /proc/mounts)"
echo "$basename: $rootdev $mode"

