#!/bin/sh

  DEFAULT_ROOTHOME=/tmp
  DEFAULT_HOSTNAME=ltq
  DEFAULT_TZ="CET-1CEST,M3.5.0,M10.5.0/3"
  DEFAULT_ZONENAME="Europe/Amsterdam"

  DEFAULT_ROOT_PW=root

#- set default root passwort to root, if empty and set root to /tmp
  if grep ^root:: /etc/shadow > /dev/null; then
    ( echo root; echo "$DEFAULT_ROOT_PW"; ) | passwd root
    /etc/init.d/telnet stop > /dev/null 2>&1
    sed -i -r -e '/^root/ s@(root:[^:]+:[0-9]+:[0-9]+:[^:]+):[^:]+:(.*$)@\1:'"$DEFAULT_ROOTHOME"':\2@' /etc/passwd
  fi
  rm -f /init

#- generate sane defaults to hostname and TZ
  uci set system.@system[0].hostname="$DEFAULT_HOSTNAME"
  sysctl -w kernel.hostname="$DEFAULT_HOSTNAME"

  uci set system.@system[0].timezone="$DEFAULT_TZ"
  echo "$DEFAULT_TZ" > /var/TZ
  uci set system.@system[0].zonename="$DEFAULT_ZONENAME"
  ln -sf /usr/share/zoneinfo/$DEFAULT_ZONENAME /tmp/localtime


#- uci modifications
  #- disable wifi
    uci set wireless.radio0.disabled=1
    #uci set wireless.radio0.country=DE
    #uci set wireless.radio0.country=JP
  #- disable atm
    #uci set network.atm.auto=0
    #uci delete network.atm
  #- set correct ANNEX
    #uci set network.dsl.annex=b
    #uci set network.dsl.tone=bv
    #uci set network.dsl.xfer_mode=ptm
  #- prevent autostart of wan with bad defaults
    uci set network.wan.auto=0
    uci set network.wan6.auto=0
  #- set ptm mode
    #uci set network.wan.ifname=ptm0
  #- local wireless defaults
    uci set wireless.@wifi-iface[0].mode=ap
    uci set wireless.@wifi-iface[0].ssid=ltq
    uci set wireless.@wifi-iface[0].encryption="mixed-psk+ccmp"
    uci set wireless.@wifi-iface[0].key="lantiqXRX!"

#- uci commit
  uci commit

