#!/bin/sh

  DEFAULT_ROOTHOME=/tmp
  DEFAULT_HOSTNAME=dockstar
  DEFAULT_TZ="CET-1CEST,M3.5.0,M10.5.0/3"
  DEFAULT_ZONENAME="Europe/Amsterdam"

  RC_TO_DISABLE=
  RC_TO_DISABLE="$RC_TO_DISABLE qos"
  RC_TO_DISABLE="$RC_TO_DISABLE firewall"
  RC_TO_DISABLE="$RC_TO_DISABLE siproxd"
  RC_TO_DISABLE="$RC_TO_DISABLE openvpn"
  RC_TO_DISABLE="$RC_TO_DISABLE fastd"
  RC_TO_DISABLE="$RC_TO_DISABLE telnet"
  RC_TO_DISABLE="$RC_TO_DISABLE nfsd"
  RC_TO_DISABLE="$RC_TO_DISABLE portmap"
  RC_TO_DISABLE="$RC_TO_DISABLE btrfs-scan"
  RC_TO_DISABLE="$RC_TO_DISABLE usbmode"
  RC_TO_DISABLE="$RC_TO_DISABLE ipset-dns"

#- set default root passwort to root, if empty and set root to /tmp
  if grep ^root:: /etc/shadow > /dev/null; then
    echo root:root | chpasswd && /etc/init.d/telnet stop > /dev/null 2>&1
    sed -i -r -e '/^root/ s@(root:[^:]+:[0-9]+:[0-9]+:[^:]+):[^:]+:(.*$)@\1:'"$DEFAULT_ROOTHOME"':\2@' /etc/passwd
  fi

#- generate sane defaults to hostname and TZ
  uci set system.@system[0].hostname="$DEFAULT_HOSTNAME"
  sysctl -w kernel.hostname="$DEFAULT_HOSTNAME"

  uci set system.@system[0].timezone="$DEFAULT_TZ"
  echo "$DEFAULT_TZ" > /var/TZ
  uci set system.@system[0].zonename="$DEFAULT_ZONENAME"
  ln -sf /usr/share/zoneinfo/$DEFAULT_ZONENAME /tmp/localtime

#- disable services
  local _rc
  for _rc in $RC_TO_DISABLE; do
    if [ -x /etc/init.d/$_rc ]; then
      /etc/init.d/$_rc disable || :
    fi
  done
  rm -f /init

#- uci commit
  uci commit

