#!/bin/sh /etc/rc.common
# Copyright (C) 2016 OpenWrt.org

# start after and stop before networking
START=30
STOP=
PIDCOUNT=0

USE_PROCD=1
PROG=/usr/sbin/agetty
SPEED_DEFAULT=115200
LOGIN=/bin/login.sh

TTY="${initscript##*/}"
SPEED="${TTY#*@}"
[ "$TTY" = "$SPEED" ] && SPEED="$SPEED_DEFAULT" || TTY="${TTY%%@*}"

if ! [ -c "/dev/$TTY" ]; then
  case "(readlink -f "/proc/self/fd/1")" in
    /dev/tty* ) echo "E: /dev/$TTY is not an character device." ;;
  esac
fi >&2

start_service() {
  procd_open_instance
  procd_set_param command
  procd_append_param command "/usr/bin/pgrphack"
  procd_append_param command "$PROG"
  procd_append_param command -8 -i -l /bin/login.sh -a root -p -L
  procd_append_param command "$TTY" "$SPEED" vt100
  procd_set_param respawn
  procd_close_instance
}

