#!/bin/sh /etc/rc.common

START=99
PATH=/usr/local/sbin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin

OPKG_DEST=ram
RAM_DIR="$(grep "dest $OPKG_DEST" /etc/opkg.conf | cut -f 3 -d " " )"
RAM_DIR="${RAM_DIR%/}"

PKG_LIST=/etc/ram-pkg.list

boot() {
  exec > /var/run/ram-pkg.boot.log 2>&1
  echo "--- $(date)"
  set -x
  start &
}
restart() { start; }
reload() { start; }

wait_opkg_list_update() {
  while ! P update > /dev/null 2> /dev/null; do
    sleep 30
  done
}

list_installed_autostart_svcs() {
  local i l
  for i in "$RAM_DIR/etc/init.d"/*; do
    i="${i#$RAM_DIR}"
    [ -x "$i" ] || \
      continue
    l="${i##*/}"
    ls -l /etc/rc.d/S* | awk '/..\/init.d\/'"$l"'/ {print $(NF-2)}'
  done | sort -n
}

list_installed_svcs() {
  local i l
  for i in "$RAM_DIR/etc/init.d"/*; do
    i="${i#$RAM_DIR}"
    [ -x "$i" ] || \
      continue
    l="${i##*/}"
    ls -1 /etc/rc.d/K??$l "/etc/init.d/$l" "$RAM_PKG/etc/init.d/$l" 2> /dev/null | head -n 1
  done | sort -n
}

start_installed_autostart_svcs() {
  list_installed_autostart_svcs | while read f; do
    echo "I: $f $action"
    "$f" "$action" || :
  done
}

stop_installed_autostop_svcs() {
  list_installed_svcs | while read f; do
    echo "I: $f $action"
    "$f" "$action"
  done
}

start() {
  local pkgs="$(grep -v ^# "$PKG_LIST" 2> /dev/null | grep -Ev '^ *$')"
  if [ -n "$pkgs" ]; then
    wait_opkg_list_update
    if P install $pkgs; then
      start_installed_autostart_svcs
    fi
  fi
}

stop() {
  local pkgs="$(P status 2> /dev/null | cut -f1 -d' ')"
  if [ -n "$pkgs" ]; then
    stop_installed_autostop_svcs "$action"
    P remove $pkgs
  fi
}
