#!/bin/sh

DEBUG=no # no # yes                # set -x
SHELL_1ST=no             # exec to /bin/sh on first run

#INIT=/bin/sh             # debugging
#INIT=/bin/bash             # debugging
INIT=/sbin/init          # OpenWrt 12.09 Attitude Adjustment, generic
#INIT=/sbin/procd         # OpenWrt Barrier Breaker
#INIT=/lib/procd          # OpenWrt Barrier Breaker (modified)

PATH=/bin:/sbin:/usr/bin:/usr/sbin

if ! [ $$ = 1 ]; then
  echo "$0: not run as PID 1"
  exit 1
fi >&2

[ "$DEBUG" = yes ] && set -x

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mount -t proc proc /proc
trap "ifconfig eth0 192.168.1.1; ifconfig lo 127.0.0.1; telnetd -l /bin/login.sh & exec /bin/sh" EXIT
set -e

[ "$SHELL_1ST" = yes ] && exec /bin/sh

killall hotplug2 2> /dev/null || :
killall procd 2> /dev/null || :
killall ubusd 2> /dev/null || :
killall netifd 2> /dev/null || :
busybox mount -o move /mnt/dev /dev || :
[ -c /dev/console ] &&  exec < /dev/console 1>/dev/console 2>/dev/console
busybox mount -o move /mnt/sys /sys
busybox mount -o move /mnt/tmp /tmp
busybox umount /mnt/proc

busybox mount -o move /mnt/rom /mnt
busybox umount /mnt
busybox mount -o move /mnt/overlay /mnt
busybox umount /mnt || :
busybox umount /mnt || :

#- remount RW
#       busybox mount -o remount,compress=lzo /
       busybox mount -o remount,noatime /
#       busybox mount -o remount,ro /
       busybox mount -o remount,rw /
chmod 1777 /tmp/.

#- cleanup traps
trap "" EXIT

#- init, procd or debugging shell
if [ -x "$INIT" ]; then
  exec "$INIT"
fi

exec /bin/sh

