#!/bin/sh -e

if ! [ $$ = 1 ]; then
  echo "$0[$$]: not started as PID 1."
  exit 1
fi >&2

if [ -L /proc/self/fd/3 ]; then
  echo -n V >&3 && exec 3<&- || : ;
  echo "$0[$$]: disabled watchdog." || :
fi

#exec /sbin/init-jffs2           # search for init on jffs2 prepared usb stick
exec /sbin/init-genfs           # search for init on jffs2 prepared usb stick

# falltrough
exec /bin/sh                   # debugging shell

