#!/bin/sh

#set -e
#set -x 

confdir="."
rulesdir="."
libdir="./lib"

tables="filter"

conffile="${confdir}/pf6.conf"

. "${confdir}/${conffile}" 
. "${libdir}/functions.sh"

rulesfile="${cachedir}/pf.rules"
mkdir -p "${cachedir}"

[ -x "${libdir}/$(basename "${1}")" ] || {
	echo "$0: function does not exist."
	exit 1
} >&2 && {
	. "${libdir}/$(basename "${1}")"
}


